name: Build [Linux]

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false && (github.event_name == 'workflow_dispatch' || !contains(github.event.head_commit.message, 'noci')) }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up JDKs
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: |
          22
          21

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v3

    - name: Install desktop-file-utils, appstream
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: desktop-file-utils appstream

    - name: Download appimagetool
      run: wget https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool

    - name: Grant execute permission for appimagetool
      run: chmod +x /usr/local/bin/appimagetool

    - name: Build AppImage
      run: ./gradlew desktopApp:packageReleaseAppImage

    - name: Upload AppImage artifact
      uses: actions/upload-artifact@v3
      with:
        name: spmp-linux-release
        path: desktopApp/build/compose/binaries/main-release/appimage/*.appimage
