name: Build [Linux]

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Install desktop-file-utils, appstream
      run: sudo apt-get install desktop-file-utils appstream

    - name: Download appimagetool
      run: wget https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool

    - name: Grant execute permission for appimagetool
      run: chmod +x /usr/local/bin/appimagetool

    - name: Build AppImage
      run: ./gradlew desktopApp:packageReleaseAppImage

    - name: Upload AppImage artifact
      uses: actions/upload-artifact@v3
      with:
        name: spmp-linux-release
        path: desktopApp/build/compose/binaries/main-release/appimage/*.appimage
